from fastapi import FastAPI, HTTPException, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
from typing import List
import json
import uuid
import os

from models import Case, Policy, Verdict, CaseInput
from adjudication import get_verdict
from case_maker import parse_documents_to_case
from database import db

app = FastAPI(title="Plum Claim Engine API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def read_root():
    return {"message": "Welcome to Plum Claim Engine Backend"}

@app.post("/api/v1/adjudicate", response_model=Verdict)
def adjudicate_claim(payload: dict):
    try:
        case_data = payload.get("case")
        policy_data = payload.get("policy")
        
        if not case_data:
            raise HTTPException(status_code=400, detail="Case data required")
            
        if not policy_data:
            # Load default policy from json
            policy_path = os.path.join(os.path.dirname(__file__), '..', 'Project_information', 'policy_terms.json')
            with open(policy_path, 'r') as f:
                policy_data = json.load(f)
                
        case = Case(**case_data)
        policy = Policy(**policy_data)
        
        verdict = get_verdict(case, policy)
        
        # Save logs for future analytics, dashboards, and appeal tracking
        db.save_case_log(case.model_dump())
        db.save_verdict_log(verdict.model_dump())
        
        if verdict.decision == "MANUAL_REVIEW" and verdict.flags:
            db.save_fraud_flag(case.case_id, "; ".join(verdict.flags))
            
        return verdict
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/v1/extract")
async def extract_case_details(
    member_id: str = Form(...),
    member_name: str = Form(...),
    context: str = Form(None),
    files: List[UploadFile] = File(...)):
    
    try:
        member_info = {
            "member_id": member_id,
            "member_name": member_name,
            "context": context
        }
        
        from ocr_engine import ocr
        
        documents_texts = []
        for file in files:
            content = await file.read()
            
            # Extract actual text using OCR engine
            extracted_text = ocr.extract_text(content, file.filename)
            documents_texts.append({
                "filename": file.filename,
                "content": extracted_text
            })
            
            # Optional: Save logs to Supabase Storage if bucket exists
            if db.supabase:
                try:
                    # db.supabase.storage.from_('documents').upload(f"claims/{member_id}/{file.filename}", content)
                    pass
                except Exception as upload_err:
                    print(f"Warning: Could not upload to storage: {upload_err}")
            
        # Pass the aggregated list of dicts to parse_documents_to_case
        case_input_data = parse_documents_to_case(member_info, documents_texts)
        
        print(f"DEBUG: case_input_data type: {type(case_input_data)}")
        print(f"DEBUG: case_input_data keys: {list(case_input_data.keys()) if isinstance(case_input_data, dict) else 'Not a dict'}")
        
        case = Case(
            case_id=f"CLM_{str(uuid.uuid4())[:8].upper()}",
            case_name=f"Claim for {member_name}",
            description="Auto-generated by Plum Claim Engine Pipeline",
            input_data=CaseInput(**case_input_data)
        )
        
        # Save initial extraction log for auditability
        db.save_case_log(case.model_dump())
        
        return {"case": case.model_dump()}
        
    except Exception as e:
        print(f"Error in extraction: {e}")
        raise HTTPException(status_code=500, detail=str(e))
