from fastapi import FastAPI, HTTPException, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
from typing import List
import json
import uuid
import os

from models import Case, Policy, Verdict, CaseInput
from adjudication import get_verdict
from case_maker import parse_documents_to_case
from database import db
from pydantic import ValidationError

app = FastAPI(title="Plum Claim Engine API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def read_root():
    return {"message": "Welcome to Plum Claim Engine Backend"}

@app.post("/api/v1/adjudicate", response_model=Verdict)
def adjudicate_claim(payload: dict):
    try:
        case_data = payload.get("case")
        policy_data = payload.get("policy")
        
        if not case_data:
            raise HTTPException(status_code=400, detail="Case data required")
            
        if not policy_data:
            # Load default policy from json
            policy_path = os.path.join(os.path.dirname(__file__), '..', 'Project_information', 'policy_terms.json')
            with open(policy_path, 'r') as f:
                policy_data = json.load(f)
                
        case = Case(**case_data)
        policy = Policy(**policy_data)
        
        verdict = get_verdict(case, policy)
        
        # Save logs for future analytics, dashboards, and appeal tracking
        db.save_case_log(case.model_dump())
        db.save_verdict_log(verdict.model_dump())
        
        if verdict.decision == "MANUAL_REVIEW" and verdict.flags:
            db.save_fraud_flag(case.case_id, "; ".join(verdict.flags))
            
        return verdict
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/v1/extract")
async def extract_case_details(
    member_id: str = Form(...),
    member_name: str = Form(...),
    context: str = Form(None),
    files: List[UploadFile] = File(...)):
    
    try:
        member_info = {
            "member_id": member_id,
            "member_name": member_name,
            "context": context
        }
        
        from ocr_engine import ocr
        
        documents_texts = []
        document_urls = {}
        
        for file in files:
            content = await file.read()
            
            # 1. OCR Extraction
            extracted_text = ocr.extract_text(content, file.filename)
            documents_texts.append({
                "filename": file.filename,
                "content": extracted_text
            })
            
            # 2. Storage Upload
            if db.supabase:
                try:
                    path = f"claims/{member_id}/{str(uuid.uuid4())[:8]}_{file.filename}"
                    public_url = db.upload_document(file.filename, content, path)
                    if public_url:
                        document_urls[file.filename] = public_url
                except Exception as upload_err:
                    print(f"Warning: Could not upload to storage: {upload_err}")
            
        # 3. Parse and Create Case
        case_input_data = parse_documents_to_case(member_info, documents_texts)
        
        # Add URLs to the input data
        if "documents" in case_input_data:
            case_input_data["documents"]["document_urls"] = document_urls
            # Ensure raw_transcripts are also updated if they were missing something
            case_input_data["documents"]["raw_transcripts"] = documents_texts
        
        case = Case(
            case_id=f"CLM_{str(uuid.uuid4())[:8].upper()}",
            case_name=f"Claim for {member_name}",
            description="Auto-generated by Plum Claim Engine Pipeline",
            input_data=CaseInput(**case_input_data)
        )
        
        # Save initial extraction log
        db.save_case_log(case.model_dump())
        
        return {"case": case.model_dump()}
        
    except Exception as e:
        import traceback
        print(traceback.format_exc())
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/api/v1/policy", response_model=Policy)
def get_policy():
    try:
        policy_path = os.path.join(os.path.dirname(__file__), '..', 'Project_information', 'policy_terms.json')
        with open(policy_path, 'r') as f:
            policy_data = json.load(f)
        return Policy(**policy_data)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/v1/policy")
def update_policy(policy: Policy):
    try:
        policy_path = os.path.join(os.path.dirname(__file__), '..', 'Project_information', 'policy_terms.json')
        with open(policy_path, 'w') as f:
            json.dump(policy.model_dump(), f, indent=2)
        return {"message": "Policy updated successfully"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/api/v1/evaluation/run")
def run_evaluation():
    try:
        from evaluation_engine import EvaluationEngine
        engine = EvaluationEngine()
        results = engine.run_all_tests()
        return results
    except Exception as e:
        import traceback
        print(traceback.format_exc())
        raise HTTPException(status_code=500, detail=str(e))

# --- Admin & Review Endpoints ---

@app.get("/api/v1/admin/cases")
def get_all_cases():
    try:
        return db.get_all_cases()
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/api/v1/admin/verdicts")
def get_all_verdicts():
    try:
        return db.get_all_verdicts()
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/v1/admin/verdict/override")
def override_verdict(payload: dict):
    try:
        claim_id = payload.get("claim_id")
        updated_verdict = payload.get("verdict")
        
        if not claim_id or not updated_verdict:
            raise HTTPException(status_code=400, detail="claim_id and verdict are required")
            
        success = db.update_verdict_log(claim_id, updated_verdict)
        if success:
            return {"message": "Verdict overridden successfully"}
        else:
            raise HTTPException(status_code=404, detail="Verdict not found")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
