from fastapi import FastAPI, HTTPException, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
from typing import List
import json
import uuid

from models import Case, Policy, Verdict
from adjudication import get_verdict
from case_maker import parse_documents_to_case
from database import db

app = FastAPI(title="Plum Claim Engine API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def read_root():
    return {"message": "Welcome to Plum Claim Engine Backend"}

@app.post("/api/v1/adjudicate", response_model=Verdict)
def adjudicate_claim(payload: dict):
    try:
        case_data = payload.get("case")
        policy_data = payload.get("policy")
        
        if not case_data or not policy_data:
            raise HTTPException(status_code=400, detail="Case and Policy data required")
            
        case = Case(**case_data)
        policy = Policy(**policy_data)
        
        verdict = get_verdict(case, policy)
        
        # Save logs for future analytics, dashboards, and appeal tracking
        db.save_case_log(case.model_dump())
        db.save_verdict_log(verdict.model_dump())
        
        if verdict.decision == "MANUAL_REVIEW" and verdict.flags:
            db.save_fraud_flag(case.case_id, "; ".join(verdict.flags))
            
        return verdict
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/v1/extract")
async def extract_case_details(
    member_id: str = Form(...),
    member_name: str = Form(...),
    files: List[UploadFile] = File(...)):
    
    try:
        member_info = {
            "member_id": member_id,
            "member_name": member_name
        }
        
        documents_texts = []
        for file in files:
            content = await file.read()
            file_extension = file.filename.split('.')[-1].lower()
            
            # Save actual documents for manual review system
            if db.supabase:
                try:
                    file_path = f"claims/{member_id}/{file.filename}"
                    # We upload to a storage bucket named 'documents'
                    # db.supabase.storage.from_('documents').upload(file_path, content)
                    # print(f"Document {file.filename} saved to Supabase storage.")
                except Exception as upload_err:
                    print(f"Warning: Could not upload to storage: {upload_err}")
            
            # Normally, we'd OCR the image/pdf here. For now, we simulate extraction.
            documents_texts.append(f"Processing file: {file.filename}")
            
        case_input = parse_documents_to_case(member_info, documents_texts)
        
        case = Case(
            case_id=f"CLM_{str(uuid.uuid4())[:8].upper()}",
            case_name=f"Claim for {member_name}",
            description="Auto-generated by Case Maker Pipeline",
            input_data=case_input
        )
        
        return {"case": case.model_dump()}
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
