from enum import Enum

class Decision(str, Enum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PARTIAL = "PARTIAL"
    MANUAL_REVIEW = "MANUAL_REVIEW"

class RejectionReason(str, Enum):
    # Category 1: Eligibility
    POLICY_INACTIVE = "POLICY_INACTIVE"
    WAITING_PERIOD = "WAITING_PERIOD"
    MEMBER_NOT_COVERED = "MEMBER_NOT_COVERED"
    
    # Category 2: Documentation
    MISSING_DOCUMENTS = "MISSING_DOCUMENTS"
    ILLEGIBLE_DOCUMENTS = "ILLEGIBLE_DOCUMENTS"
    INVALID_PRESCRIPTION = "INVALID_PRESCRIPTION"
    DOCTOR_REG_INVALID = "DOCTOR_REG_INVALID"
    DATE_MISMATCH = "DATE_MISMATCH"
    PATIENT_MISMATCH = "PATIENT_MISMATCH"
    
    # Category 3: Coverage
    SERVICE_NOT_COVERED = "SERVICE_NOT_COVERED"
    EXCLUDED_CONDITION = "EXCLUDED_CONDITION"
    PRE_AUTH_MISSING = "PRE_AUTH_MISSING"
    
    # Category 4: Limits
    ANNUAL_LIMIT_EXCEEDED = "ANNUAL_LIMIT_EXCEEDED"
    SUB_LIMIT_EXCEEDED = "SUB_LIMIT_EXCEEDED"
    PER_CLAIM_EXCEEDED = "PER_CLAIM_EXCEEDED"
    
    # Category 5: Medical
    NOT_MEDICALLY_NECESSARY = "NOT_MEDICALLY_NECESSARY"
    EXPERIMENTAL_TREATMENT = "EXPERIMENTAL_TREATMENT"
    COSMETIC_PROCEDURE = "COSMETIC_PROCEDURE"
    
    # Category 6: Process
    LATE_SUBMISSION = "LATE_SUBMISSION"
    DUPLICATE_CLAIM = "DUPLICATE_CLAIM"
    BELOW_MIN_AMOUNT = "BELOW_MIN_AMOUNT"
    FUTURE_DATE = "FUTURE_DATE"
